const products = [
  {
    id: "1",
    name: "Galaxy S22",
    category: "phones",
    price: 799,
    image:
      "https://hotstore.hotmobile.co.il/media/catalog/product/cache/a73c0d5d6c75fbb1966fe13af695aeb7/h/6/h69115529_1000x1000_13.2_new2_2.png",
    company: "Samsung",
    screen: "6.1 inches Super AMOLED",
    processor: "Snapdragon 8 Gen 1",
    battery: "3700 mAh",
    lens: null,
    inches: null,
    graphicCard: null,
    output: null,
    storage: null,
    engine: null,
    capacity: null,
    weight: null,
    connections: null,
    rating: 0,
  },
  {
    id: "2",
    name: "Canon EOS R6",
    category: "cameras",
    price: 2499,
    image:
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/https://www.payngo.co.il/media/catalog/product/4/0/4082c002_eos-r6-body_primary.png/w_700,h_700,r_contain",
    company: "Canon",
    screen: null,
    processor: "DIGIC X",
    battery: "LP-E6NH",
    lens: "RF 24-105mm f/4L IS USM",
    inches: null,
    graphicCard: null,
    output: null,
    storage: null,
    engine: null,
    capacity: null,
    weight: null,
    connections: null,
    rating: 0,
  },
  {
    id: "3",
    name: 'LG OLED CX 55" ',
    category: "screens",
    price: 1499,
    image:
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/https://www.payngo.co.il/media/catalog/product/5/5/55ur80006lj10.png/w_700,h_700,r_contain",
    company: "LG",
    screen: '55" OLED',
    output: "4K",
    inches: 55,
    lens: null,
    processor: null,
    battery: null,
    graphicCard: null,
    storage: null,
    engine: null,
    capacity: null,
    weight: null,
    connections: null,
    rating: 0,
  },
  {
    id: "4",
    name: 'MacBook Pro 14"',
    category: "computers",
    price: 1999,
    image:
      "https://buyiphone.co.il/wp-content/uploads/2023/02/mbp14-spacegray-select-202301.jpeg",
    company: "Apple",
    screen: '14.2" Liquid Retina XDR display',
    processor: "M1 Pro chip",
    battery: "70Wh",
    graphicCard: "Integrated GPU",
    storage: "512GB SSD",
    lens: null,
    inches: null,
    output: null,
    engine: null,
    capacity: null,
    weight: null,
    connections: null,
    rating: 0,
  },
  {
    id: "5",
    name: "GE Top Freezer ",
    category: "refrigirates",
    price: 368,
    image:
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/https://www.payngo.co.il/media/catalog/product/b/e/beko-1.png/w_700,h_700,r_contain",
    company: "GE",
    capacity: "18 cu. ft.",
    engine: "Top freezer",
    weight: "161 lbs",
    screen: null,
    processor: null,
    battery: null,
    graphicCard: null,
    storage: null,
    lens: null,
    inches: null,
    output: null,
    connections: null,
    rating: 0,
  },
  {
    id: "6",
    name: "Midea U Inverter Window AC",
    category: "AC",
    price: 389,
    image:
      "https://d1pjg4o0tbonat.cloudfront.net/content/dam/midea-aem/us/air-conditioners/window-air-conditioners/8000-btu-u-shaped-air-conditioner-maw08v1qwt/gallery3.jpg/jcr:content/renditions/cq5dam.web.5000.5000.jpeg",
    company: "Midea",
    capacity: "12000 BTU",
    weight: "81 lbs",
    connections: "Wall sleeve kit included",
    screen: null,
    processor: null,
    battery: null,
    graphicCard: null,
    storage: null,
    lens: null,
    inches: null,
    output: null,
    engine: null,
    rating: 0,
  },
  {
    id: "7",
    name: "Playstation 5",
    category: "game consoles",
    price: 499,
    image:
      "https://exongames.co.il/cdn/shop/products/sonyps5digital.jpg?v=1686148229&width=900",
    company: "Sony",
    processor: "AMD Zen 2-based CPU",
    graphicCard: "10.28 TFLOPS, 36 CUs at 2.23GHz Custom RDNA 2 GPU",
    storage: "825GB SSD",
    output: "Up to 8K, 120fps, ray tracing",
    screen: null,
    battery: null,
    lens: null,
    inches: null,
    engine: null,
    capacity: null,
    weight: null,
    connections: null,
    rating: 0,
  },
  {
    id: "8",
    name: "Fossil Gen 5 Smartwatch",
    category: "watches",
    price: 259,
    image: "",
    company: "Fossil",
    screen: '1.3" AMOLED display',
    battery: "24+ hour battery",
    processor: "Qualcomm Snapdragon Wear 3100",
    storage: "8GB",
    lens: null,
    inches: null,
    graphicCard: null,
    output: null,
    engine: null,
    capacity: null,
    weight: null,
    connections: null,
    rating: 0,
  },
  {
    id: "9",
    name: "iPhone 14 Pro",
    category: "phones",
    price: 999,
    image: "",
    company: "Apple",
    screen: '6.1" Super Retina XDR display',
    processor: "A16 Bionic chip",
    battery: "Up to 29 hours video playback",
    lens: null,
    inches: null,
    graphicCard: null,
    output: null,
    storage: null,
    engine: null,
    capacity: null,
    weight: null,
    connections: null,
    rating: 0,
  },
];

export default products;
