const products = [
    {
      id: "1",
      name: "Galaxy S22",
      category: "phones",
      price: 799,
      image:
        "https://images.samsung.com/is/image/samsung/p6pim/nz/2202/gallery/nz-galaxy-s22-s908-sm-s908nzkaxnz-531698548?$720_576_PNG$",
      company: "Samsung",
      screen: "6.1 inches Super AMOLED",
      processor: "Snapdragon 8 Gen 1",
      battery: "3700 mAh",
      lens: null,
      inches: null,
      graphicCard: null,
      output: null,
      storage: null,
      engine: null,
      capacity: null,
      weight: null,
      connections: null,
      rating: 0
    },
    {
      id: "2",
      name: "Canon EOS R6",
      category: "cameras",
      price: 2499,
      image:
        "https://www.usa.canon.com/internet/wcm/connect/us/9d47d4c9-f1fc-49ae-b7b9-e087265a3897/EOSR6-rf24-105f4-l-is-usm-frontal-angle-highres.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE.Z18_P1KGHJ01L85180BQO530QD6CR34-9d47d4c9-f1fc-49ae-b7b9-e087265a3897-mVb0nB1",
      company: "Canon",
      screen: null,
      processor: "DIGIC X",
      battery: "LP-E6NH",
      lens: "RF 24-105mm f/4L IS USM",
      inches: null,
      graphicCard: null,
      output: null,
      storage: null,
      engine: null,
      capacity: null,
      weight: null,
      connections: null,
      rating: 0
    },
    {
      id: "3",
      name: 'LG OLED CX 55" ',
      category: "screens",
      price: 1499,
      image:
        "https://images.lg.com/is/image/LGEAI/cx-55-inch-oled-tv-oled55cxpua-D-01-20200122?$720x576_jpg$",
      company: "LG",
      screen: '55" OLED',
      output: "4K",
      inches: 55,
      lens: null,
      processor: null,
      battery: null,
      graphicCard: null,
      storage: null,
      engine: null,
      capacity: null,
      weight: null,
      connections: null,
      rating: 0
    },
    {
      id: "4",
      name: 'MacBook Pro 14"',
      category: "computers",
      price: 1999,
      image:
        "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-spacegray-select-202110?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1633849625000",
      company: "Apple",
      screen: '14.2" Liquid Retina XDR display',
      processor: "M1 Pro chip",
      battery: "70Wh",
      graphicCard: "Integrated GPU",
      storage: "512GB SSD",
      lens: null,
      inches: null,
      output: null,
      engine: null,
      capacity: null,
      weight: null,
      connections: null,
      rating: 0
    },
    {
      id: "5",
      name: "GE Top Freezer Refrigerator",
      category: "refrigirates",
      price: 368,
      image:
        "https://products.geappliances.com/MarketingObjectRetrieval/Dispatcher?RequestType=Image&Name=jtm18bbww_white01.jpg&Variant=White",
      company: "GE",
      capacity: "18 cu. ft.",
      engine: "Top freezer",
      weight: "161 lbs",
      screen: null,
      processor: null,
      battery: null,
      graphicCard: null,
      storage: null,
      lens: null,
      inches: null,
      output: null,
      connections: null,
      rating: 0
    },
    {
      id: "6",
      name: "Midea U Inverter Window AC",
      category: "AC",
      price: 389,
      image: "https://m.media-amazon.com/images/I/71XNC083IrL._AC_SL1500_.jpg",
      company: "Midea",
      capacity: "12000 BTU",
      weight: "81 lbs",
      connections: "Wall sleeve kit included",
      screen: null,
      processor: null,
      battery: null,
      graphicCard: null,
      storage: null,
      lens: null,
      inches: null,
      output: null,
      engine: null,
      rating: 0
    },
    {
      id: "7",
      name: "Playstation 5",
      category: "game consoles",
      price: 499,
      image: "https://m.media-amazon.com/images/I/71p+19Uc8PL._AC_SL1500_.jpg",
      company: "Sony",
      processor: "AMD Zen 2-based CPU",
      graphicCard: "10.28 TFLOPS, 36 CUs at 2.23GHz Custom RDNA 2 GPU",
      storage: "825GB SSD",
      output: "Up to 8K, 120fps, ray tracing",
      screen: null,
      battery: null,
      lens: null,
      inches: null,
      engine: null,
      capacity: null,
      weight: null,
      connections: null,
      rating: 0
    },
    {
      id: "8",
      name: "Fossil Gen 5 Smartwatch",
      category: "watches",
      price: 259,
      image:
        "https://fossil.scene7.com/is/image/FossilPartners/FTW4042_main?$sfcc_fos_hi-res$",
      company: "Fossil",
      screen: '1.3" AMOLED display',
      battery: "24+ hour battery",
      processor: "Qualcomm Snapdragon Wear 3100",
      storage: "8GB",
      lens: null,
      inches: null,
      graphicCard: null,
      output: null,
      engine: null,
      capacity: null,
      weight: null,
      connections: null,
      rating: 0
    },
    {
      id: "9",
      name: "iPhone 14 Pro",
      category: "phones",
      price: 999,
      image:
        "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-card-40-iphone14pro-202209?wid=470&hei=556&fmt=jpeg&qlt=95&.v=1663614745409",
      company: "Apple",
      screen: '6.1" Super Retina XDR display',
      processor: "A16 Bionic chip",
      battery: "Up to 29 hours video playback",
      lens: null,
      inches: null,
      graphicCard: null,
      output: null,
      storage: null,
      engine: null,
      capacity: null,
      weight: null,
      connections: null,
      rating: 0
    },
  ];

export default products